// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppwatjhahicuwnvlpzqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwd2F0amhhaGljdXdudmxwenFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzAxMzEsImV4cCI6MjA2OTQ0NjEzMX0.9TnpvZQGZwYuA-yiLxqi29XgqFmaehgqEh4udTTMnUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});